### ISSUE TITLE
PathEx butchers URLs

### ISSUE THREAD

**Issue by nsheff** [pepkit/attmap#46]
Give a genome_server attribute with a URL like `http://localhost` and the PathEx functionality of attmap is removing the double-slash, rendering the URL incorrect

```
In [66]: obj                                                                                                                       
Out[66]: 
YacAttMap
genome_folder: $GENOMES
genome_server: http://localhost
genomes:
  hg38:
    bowtie2: indexed_bowtie2
    hisat2: indexed_hisat2
    tss_annotation: TSS.bed.gz
    gtf: blah.gtf
  mm10:
    bowtie2: indexed_bowtie2
    blacklist: blacklist/mm10.bed
  rCRSd:
    bowtie2: indexed_bowtie2
    bowtie: indexed_bowtie

In [67]: obj.genome_server                                                                                                         
Out[67]: 'http:/localhost'
```

is there any way to do a url-aware path expansion that will expand env variables, but not ruin urls?

using version 0.11
